emb-net:
  - dim: 200
    dim_e: 200
    dim_t: 100
    history: 1
    layer: 1
    sample: '-1'
gen-net:
  - dim_r: 200
    arch: 'dense-dense-dense'
    dim: '1024-1024-2048'
    att_head: '0-0-0'
    history: '31 23 15 7 3 1 0'
    copy: 0.99
train:
  - fwd: 107
    epoch: 80
    batch_size: 1024
    lr: 0.0015
    dropout: 0.45
    weight_decay: 0.00001

# run1:
#   raw: MRR 0.4593 hit3: 0.5143 hit10: 0.6161
#   fil: MRR 0.6612 hit3: 0.6645 hit10: 0.6837
# run2:
#   raw: MRR 0.4602 hit3: 0.5119 hit10: 0.6179
#   fil: MRR 0.6630 hit3: 0.6647 hit10: 0.6837
# run3:
#   raw: MRR 0.4608 hit3: 0.5141 hit10: 0.6170
#   fil: MRR 0.6609 hit3: 0.6631 hit10: 0.6843